"""FASE 15 - Figures generated by code from already-executed outputs. English labels."""
import pandas as pd
import numpy as np
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from pathlib import Path

PROCESSED = Path(r"D:/ACADEMICO/Papers/TBI_data_analysis/data/processed")
EXPLORATORY = Path(r"D:/ACADEMICO/Papers/TBI_data_analysis/results/exploratory")
TABLES = Path(r"D:/ACADEMICO/Papers/TBI_data_analysis/tables")
FIG = Path(r"D:/ACADEMICO/Papers/TBI_data_analysis/figures")
FIG.mkdir(parents=True, exist_ok=True)
plt.rcParams["font.size"] = 10


def fig1_national_trend():
    df = pd.read_csv(PROCESSED / "rq1_panel_dept_year.csv").dropna(subset=["poblacion_total"])
    nat = df.groupby("year").agg(n=("n_fatal_moto", "sum"), n_tce=("n_fatal_moto_tce", "sum")).reset_index()
    nat["pct_tce"] = 100 * nat["n_tce"] / nat["n"]

    fig, ax1 = plt.subplots(figsize=(7, 4.5))
    ax1.bar(nat["year"], nat["n"], color="#4C72B0", alpha=0.85, label="Motorcyclist deaths (total)")
    ax1.bar(nat["year"], nat["n_tce"], color="#C44E52", alpha=0.9, label="Motorcyclist deaths with TBI")
    ax1.set_ylabel("Number of deaths")
    ax1.set_xlabel("Year")
    ax1.axvline(2021.5, color="gray", linestyle="--", linewidth=1)
    ax1.text(2021.6, ax1.get_ylim()[1] * 0.92, "DANE 2022\nbreak", fontsize=8, color="gray")
    ax1.legend(loc="upper left", fontsize=8)

    ax2 = ax1.twinx()
    ax2.plot(nat["year"], nat["pct_tce"], color="black", marker="o", markersize=4, linewidth=1.5)
    ax2.set_ylabel("% TBI among motorcyclist deaths")
    ax2.set_ylim(0, 60)

    ax1.set_title("Motorcyclist mortality and share with TBI, Colombia 2015-2024\n(Source: Medicina Legal)")
    fig.tight_layout()
    fig.savefig(FIG / "fig1_tendencia_nacional.png", dpi=150)
    plt.close(fig)
    print("fig1 saved")


def fig2_departments():
    rates = pd.read_csv(EXPLORATORY / "rq1_tasas_departamento.csv")
    rates = rates.sort_values("tasa_fatal_moto_x100k", ascending=True)
    fig, ax = plt.subplots(figsize=(6, 9))
    colors = ["#C44E52" if v >= rates["tasa_fatal_moto_x100k"].median() else "#4C72B0"
              for v in rates["tasa_fatal_moto_x100k"]]
    ax.barh(rates["depto_nombre_medlegal"], rates["tasa_fatal_moto_x100k"], color=colors)
    ax.set_xlabel("Mean annual rate 2015-2024 (motorcyclist deaths per 100,000 pop.)")
    ax.set_title("Territorial inequality: motorcyclist mortality by department")
    fig.tight_layout()
    fig.savefig(FIG / "fig2_tasas_departamento.png", dpi=150)
    plt.close(fig)
    print("fig2 saved")


def fig3_forest_case_fatality():
    """Refits the model (identical to script 08, h3_letalidad) to extract EXACT OR and 95% CI
    from the fitted object -- values are never transcribed by hand."""
    df = pd.read_csv(PROCESSED / "rq2_individual_moto_tce.csv")
    df["zona_bin"] = np.where(df["zona"].astype(str).str.contains("rural", case=False, na=False), "Rural",
                       np.where(df["zona"].astype(str).str.contains("Cabecera", na=False), "Urbano", "Otro"))
    df = df[df["zona_bin"] != "Otro"]
    df["year_c"] = df["year"] - df["year"].min()
    import statsmodels.api as sm
    import statsmodels.formula.api as smf
    m = smf.glm("outcome_fatal ~ sexo + zona_bin + rol + year_c", data=df, family=sm.families.Binomial()).fit()
    ci_df = np.exp(m.conf_int())
    or_df = np.exp(m.params)

    keys = ["sexo[T.Mujer]", "zona_bin[T.Urbano]", "rol[T.Pasajero]"]
    labels = ["Sex: Female\n(vs. Male)", "Zone: Urban\n(vs. Rural)", "Role: Passenger\n(vs. Driver)"]
    or_point = [or_df[k] for k in keys]
    ci_low = [ci_df.loc[k, 0] for k in keys]
    ci_high = [ci_df.loc[k, 1] for k in keys]

    fig, ax = plt.subplots(figsize=(6, 3.5))
    y = np.arange(len(labels))
    ax.errorbar(or_point, y, xerr=[np.array(or_point) - np.array(ci_low), np.array(ci_high) - np.array(or_point)],
                fmt="o", color="black", capsize=4)
    ax.axvline(1, color="gray", linestyle="--")
    ax.set_yticks(y)
    ax.set_yticklabels(labels)
    ax.set_xlabel("Odds ratio (fatal outcome among registered motorcyclist TBI cases)")
    ax.set_title("Factors associated with fatal outcome (RQ2, secondary)")
    fig.tight_layout()
    fig.savefig(FIG / "fig3_forest_letalidad.png", dpi=150)
    plt.close(fig)
    print("fig3 saved (exact model OR/CI, not approximated)")


def figS_runt_sensitivity():
    df = pd.read_csv(TABLES / "tableS_runt_sensibilidad.csv").dropna(subset=["tasa_x10k_moto"])
    from scipy.stats import spearmanr
    rho, _ = spearmanr(df["tasa_x100k_hab"], df["tasa_x10k_moto"])
    fig, ax = plt.subplots(figsize=(7, 5.5))
    robust = df["robusto_alto"] == True
    ax.scatter(df.loc[~robust, "tasa_x100k_hab"], df.loc[~robust, "tasa_x10k_moto"],
               color="#4C72B0", alpha=0.7, label="Other departments")
    ax.scatter(df.loc[robust, "tasa_x100k_hab"], df.loc[robust, "tasa_x10k_moto"],
               color="#C44E52", s=60, label="Robust (top tertile in both)")
    for _, r in df.iterrows():
        ax.annotate(r["depto"], (r["tasa_x100k_hab"], r["tasa_x10k_moto"]),
                    fontsize=6, alpha=0.75, xytext=(3, 2), textcoords="offset points")
    ax.set_xlabel("Rate per 100,000 population")
    ax.set_ylabel("Rate per 10,000 registered motorcycles")
    ax.set_title(f"Exposure-denominator sensitivity by department\n(Spearman rho = {rho:.2f}, n = {int(robust.count())})")
    ax.legend(fontsize=8)
    fig.tight_layout()
    fig.savefig(FIG / "figS_runt_sensibilidad.png", dpi=150)
    plt.close(fig)
    print("figS saved")


if __name__ == "__main__":
    fig1_national_trend()
    fig2_departments()
    fig3_forest_case_fatality()
    figS_runt_sensitivity()
